version: 0.1

phases:
  install:
    commands:
      - yum install zip -y
  build:
    commands:
      - echo `pwd`
      - mkdir build
  post_build:
    commands:
      - echo Post-Build completed on `date`
      #Zip File
      - zip -r ./build/lambda.zip helloworld.py
      - ls -R *
      #Copy to S3
      #- aws s3 cp lambda.zip s3://web-dev-lambda-codebuild-s3/
artifacts:
  files:
    - 'build/*'
  name: /
